openapi: 3.0.1
info:
  title: loyalty-card API
  description: API to return discount percentage based on customer ID
  version: 1.0.0
paths:
  /discount:
    get:
      summary: Get discount percentage for a customer
      parameters:
        - name: customerId
          in: query
          required: true
          schema:
            type: string
          description: The ID of the customer
      responses:
        '200':
          description: Discount percentage
          content:
            application/json:
              schema:
                type: object
                properties:
                  discount:
                    type: number
                    format: float
                    example: 0.5
        '400':
          description: Invalid customer ID supplied
        '404':
          description: Customer not found
  /loyaltyCard:
    post:
      summary: Set a customers~ loyalty card
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: string
                loyaltyCard:
                  type: boolean
              required:
                - customerId
                - loyaltyCard
      responses:
        '200':
          description: Loyalty card set successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /customer:
    get:
      summary: Retrieve all customer data and their favorite items
      responses:
        '200':
          description: List of all customers with their favorite items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    email:
                      type: string
                    has_loyalty_card:
                      type: boolean
                    favorite_item:
                      type: string
                      example: "Meatballs"
        '404':
          description: No customers found
